In [17]:
import mahotas
import cv2

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import os
import glob

print(sys.path)
print(os.getcwd())

['D:\\Study\\Project\\AOI', 'C:\\Users\\aaronlin\\.conda\\envs\\project_AOI\\python38.zip', 'C:\\Users\\aaronlin\\.conda\\envs\\project_AOI\\DLLs', 'C:\\Users\\aaronlin\\.conda\\envs\\project_AOI\\lib', 'C:\\Users\\aaronlin\\.conda\\envs\\project_AOI', '', 'C:\\Users\\aaronlin\\AppData\\Roaming\\Python\\Python38\\site-packages', 'C:\\Users\\aaronlin\\.conda\\envs\\project_AOI\\lib\\site-packages', 'C:\\Users\\aaronlin\\.conda\\envs\\project_AOI\\lib\\site-packages\\win32', 'C:\\Users\\aaronlin\\.conda\\envs\\project_AOI\\lib\\site-packages\\win32\\lib', 'C:\\Users\\aaronlin\\.conda\\envs\\project_AOI\\lib\\site-packages\\Pythonwin']
D:\Study\Project\AOI

In [21]:
path_lst=[]
for f in glob.glob('Data(image)/train/full/*.png'): ###train_image改成放所有圖片的資料夾
    path_lst.append(f)
    
f1=f2=f3=f4=f5=f6=f7=f8=f9=f10=f11=f12=f13=np.empty(0)

for image in path_lst:
    img = cv2.imread(image)
    feature = mahotas.features.haralick(img).mean(axis =0)

    f1 = np.append(f1,feature[0])
    f2 = np.append(f2,feature[1])
    f3 = np.append(f3,feature[2])
    f4 = np.append(f4,feature[3])
    f5 = np.append(f5,feature[4])
    f6 = np.append(f6,feature[5])
    f7 = np.append(f7,feature[6])
    f8 = np.append(f8,feature[7])
    f9 = np.append(f9,feature[8])
    f10 = np.append(f10,feature[9])
    f11 = np.append(f11,feature[10])
    f12 = np.append(f12,feature[11])
    f13 = np.append(f13,feature[12])

In [22]:
df_full = pd.DataFrame([f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,f11,f12,f13], 
             index = ['f1','f2','f3','f4','f5','f6','f7','f8','f9','f10','f11','f12','f13']).transpose()
df_full

,f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,f11,f12,f13
0,0.001354,659.317620,0.157167,391.132306,0.121252,346.768587,905.211606,6.840575,12.089976,0.000363,5.347827,-0.082894,0.322514
1,0.001497,91.209170,0.909179,502.079395,0.200690,358.785207,1917.108412,7.329339,11.208077,0.000504,4.005631,-0.258346,0.955826
2,0.005265,3.084968,0.995852,371.720231,0.523585,357.885009,1483.795954,6.817557,8.538440,0.001253,1.953340,-0.552947,0.998845
3,0.003159,4.283336,0.996857,681.378381,0.491811,413.949971,2721.230186,7.505229,9.382262,0.001118,2.151092,-0.579267,0.999610
4,0.003536,2.498093,0.997002,416.623572,0.555521,406.948885,1663.996196,7.267164,8.833541,0.001332,1.835799,-0.609052,0.999660
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,0.001614,66.861090,0.950800,679.505644,0.215053,351.011115,2651.161484,7.339455,11.037201,0.000535,3.817436,-0.289416,0.973065
1496,0.001704,364.121754,0.447507,329.527395,0.138495,332.144321,953.987826,6.729030,11.561065,0.000392,4.944068,-0.101119,0.539414
1497,0.001199,67.339221,0.949033,660.564422,0.211137,331.220127,2574.918467,7.619690,11.357897,0.000530,3.829255,-0.308643,0.982119
1498,0.001740,18.464517,0.980740,479.347234,0.308725,326.214935,1898.924419,7.386130,10.281776,0.000733,3.010831,-0.411167,0.995243
1499,0.003303,14.546463,0.961501,188.949583,0.341687,333.356969,741.251869,6.695808,9.390440,0.000837,2.829086,-0.377375,0.986744

In [55]:
df_full.rename(columns= lambda x:'full_' + x, inplace = True)
df_full

,full_f1,full_f2,full_f3,full_f4,full_f5,full_f6,full_f7,full_f8,full_f9,full_f10,full_f11,full_f12,full_f13
0,0.001354,659.317620,0.157167,391.132306,0.121252,346.768587,905.211606,6.840575,12.089976,0.000363,5.347827,-0.082894,0.322514
1,0.001497,91.209170,0.909179,502.079395,0.200690,358.785207,1917.108412,7.329339,11.208077,0.000504,4.005631,-0.258346,0.955826
2,0.005265,3.084968,0.995852,371.720231,0.523585,357.885009,1483.795954,6.817557,8.538440,0.001253,1.953340,-0.552947,0.998845
3,0.003159,4.283336,0.996857,681.378381,0.491811,413.949971,2721.230186,7.505229,9.382262,0.001118,2.151092,-0.579267,0.999610
4,0.003536,2.498093,0.997002,416.623572,0.555521,406.948885,1663.996196,7.267164,8.833541,0.001332,1.835799,-0.609052,0.999660
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,0.001614,66.861090,0.950800,679.505644,0.215053,351.011115,2651.161484,7.339455,11.037201,0.000535,3.817436,-0.289416,0.973065
1496,0.001704,364.121754,0.447507,329.527395,0.138495,332.144321,953.987826,6.729030,11.561065,0.000392,4.944068,-0.101119,0.539414
1497,0.001199,67.339221,0.949033,660.564422,0.211137,331.220127,2574.918467,7.619690,11.357897,0.000530,3.829255,-0.308643,0.982119
1498,0.001740,18.464517,0.980740,479.347234,0.308725,326.214935,1898.924419,7.386130,10.281776,0.000733,3.010831,-0.411167,0.995243
1499,0.003303,14.546463,0.961501,188.949583,0.341687,333.356969,741.251869,6.695808,9.390440,0.000837,2.829086,-0.377375,0.986744

In [26]:
path_lst=[]
for f in glob.glob('Data(image)/train/leftbottom/*.jpg'): ###train_image改成放所有圖片的資料夾
    path_lst.append(f)

f1=f2=f3=f4=f5=f6=f7=f8=f9=f10=f11=f12=f13=np.empty(0)

for image in path_lst:
    img = cv2.imread(image)
    feature = mahotas.features.haralick(img).mean(axis =0)

    f1 = np.append(f1,feature[0])
    f2 = np.append(f2,feature[1])
    f3 = np.append(f3,feature[2])
    f4 = np.append(f4,feature[3])
    f5 = np.append(f5,feature[4])
    f6 = np.append(f6,feature[5])
    f7 = np.append(f7,feature[6])
    f8 = np.append(f8,feature[7])
    f9 = np.append(f9,feature[8])
    f10 = np.append(f10,feature[9])
    f11 = np.append(f11,feature[10])
    f12 = np.append(f12,feature[11])
    f13 = np.append(f13,feature[12])

In [27]:
df_lb = pd.DataFrame([f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,f11,f12,f13], 
             index = ['f1','f2','f3','f4','f5','f6','f7','f8','f9','f10','f11','f12','f13']).transpose()

In [56]:
df_lb.rename(columns= lambda x:'lb_' + x, inplace = True)
df_lb

,lb_f1,lb_f2,lb_f3,lb_f4,lb_f5,lb_f6,lb_f7,lb_f8,lb_f9,lb_f10,lb_f11,lb_f12,lb_f13
0,0.001460,611.142506,0.119323,346.982075,0.122891,337.954625,776.785794,6.722287,11.867373,0.000366,5.295862,-0.090939,0.456849
1,0.001581,93.214872,0.888361,417.641001,0.196503,359.210731,1577.349130,7.220664,11.104017,0.000501,4.016921,-0.247766,0.946661
2,0.007043,3.113188,0.995375,336.525297,0.523336,353.717896,1342.988001,6.527093,8.239566,0.001252,1.958243,-0.532540,0.998013
3,0.003321,4.762602,0.996498,680.511685,0.483303,412.634491,2717.284137,7.490239,9.411486,0.001083,2.214663,-0.572392,0.999566
4,0.003099,2.851437,0.997353,538.601450,0.537384,406.846609,2151.554364,7.411712,9.038738,0.001270,1.910292,-0.609671,0.999717
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,0.001450,83.628088,0.944137,748.429272,0.203152,386.798674,2910.089001,7.356206,11.155739,0.000508,3.959891,-0.279880,0.969563
1496,0.001683,406.947536,0.256871,273.825692,0.133760,332.349996,688.355232,6.641732,11.528347,0.000385,5.016650,-0.096086,0.490449
1497,0.001325,67.231827,0.939606,556.685192,0.210749,333.852177,2159.508939,7.498311,11.206771,0.000530,3.828128,-0.301572,0.979037
1498,0.001666,17.829295,0.984507,575.286555,0.311453,321.162348,2283.316924,7.450932,10.307226,0.000768,2.987981,-0.423468,0.996206
1499,0.003292,14.522450,0.959804,180.747209,0.340171,333.264665,708.466387,6.672658,9.363888,0.000895,2.829788,-0.375743,0.986386

In [28]:
path_lst=[]
for f in glob.glob('Data(image)/train/lefttop/*.jpg'): ###train_image改成放所有圖片的資料夾
    path_lst.append(f)

f1=f2=f3=f4=f5=f6=f7=f8=f9=f10=f11=f12=f13=np.empty(0)

for image in path_lst:
    img = cv2.imread(image)
    feature = mahotas.features.haralick(img).mean(axis =0)

    f1 = np.append(f1,feature[0])
    f2 = np.append(f2,feature[1])
    f3 = np.append(f3,feature[2])
    f4 = np.append(f4,feature[3])
    f5 = np.append(f5,feature[4])
    f6 = np.append(f6,feature[5])
    f7 = np.append(f7,feature[6])
    f8 = np.append(f8,feature[7])
    f9 = np.append(f9,feature[8])
    f10 = np.append(f10,feature[9])
    f11 = np.append(f11,feature[10])
    f12 = np.append(f12,feature[11])
    f13 = np.append(f13,feature[12])

In [29]:
df_lt = pd.DataFrame([f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,f11,f12,f13], 
             index = ['f1','f2','f3','f4','f5','f6','f7','f8','f9','f10','f11','f12','f13']).transpose()

In [60]:
df_lt.rename(columns= lambda x: 'lt_'+ x, inplace = True)
df_lt

,lt_f1,lt_f2,lt_f3,lt_f4,lt_f5,lt_f6,lt_f7,lt_f8,lt_f9,lt_f10,lt_f11,lt_f12,lt_f13
0,0.001427,628.711938,0.126095,359.720269,0.122036,350.929217,810.169136,6.756435,11.924437,0.000364,5.315377,-0.090977,0.458246
1,0.001287,102.691247,0.928404,717.020876,0.198995,363.483569,2765.392256,7.554556,11.428000,0.000493,4.080428,-0.280854,0.970828
2,0.003981,3.211465,0.996527,462.283283,0.517230,372.070340,1845.921667,7.069523,8.811264,0.001239,1.974455,-0.568082,0.999273
3,0.002680,3.972488,0.997081,680.961339,0.492997,409.720684,2719.872870,7.547713,9.360060,0.001148,2.090783,-0.590759,0.999678
4,0.004202,2.378289,0.996013,298.545748,0.560548,413.878141,1191.804704,7.022121,8.543734,0.001366,1.799955,-0.600869,0.999498
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,0.001657,74.517080,0.940313,624.278118,0.207800,377.827078,2422.595392,7.245912,10.992716,0.000520,3.890761,-0.275413,0.966500
1496,0.001672,414.799730,0.251413,277.045758,0.133570,327.564761,693.383303,6.646153,11.536740,0.000385,5.027297,-0.096318,0.490612
1497,0.001094,69.373448,0.956283,793.401399,0.209348,332.453911,3104.232150,7.734458,11.453576,0.000527,3.847914,-0.323092,0.986475
1498,0.002169,18.885458,0.969771,312.382161,0.306032,331.734401,1230.643186,7.084145,9.984826,0.000770,3.026315,-0.382608,0.991349
1499,0.003360,14.458180,0.960507,183.071402,0.342309,334.288699,717.827426,6.671494,9.352650,0.000874,2.822389,-0.377536,0.986475

In [30]:
path_lst=[]
for f in glob.glob('Data(image)/train/rightbottom/*.jpg'): ###train_image改成放所有圖片的資料夾
    path_lst.append(f)

f1=f2=f3=f4=f5=f6=f7=f8=f9=f10=f11=f12=f13=np.empty(0)

for image in path_lst:
    img = cv2.imread(image)
    feature = mahotas.features.haralick(img).mean(axis =0)

    f1 = np.append(f1,feature[0])
    f2 = np.append(f2,feature[1])
    f3 = np.append(f3,feature[2])
    f4 = np.append(f4,feature[3])
    f5 = np.append(f5,feature[4])
    f6 = np.append(f6,feature[5])
    f7 = np.append(f7,feature[6])
    f8 = np.append(f8,feature[7])
    f9 = np.append(f9,feature[8])
    f10 = np.append(f10,feature[9])
    f11 = np.append(f11,feature[10])
    f12 = np.append(f12,feature[11])
    f13 = np.append(f13,feature[12])

In [31]:
df_rb = pd.DataFrame([f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,f11,f12,f13], 
             index = ['f1','f2','f3','f4','f5','f6','f7','f8','f9','f10','f11','f12','f13']).transpose()

In [58]:
df_rb.rename(columns= lambda x:'rb_' + x, inplace = True)
df_rb

,rb_f1,rb_f2,rb_f3,rb_f4,rb_f5,rb_f6,rb_f7,rb_f8,rb_f9,rb_f10,rb_f11,rb_f12,rb_f13
0,0.001349,677.068876,0.149680,398.124781,0.120550,341.916972,915.430249,6.843448,12.051436,0.000362,5.365418,-0.091722,0.469381
1,0.001740,82.562571,0.883343,353.908956,0.203607,356.286137,1333.073253,7.112705,10.928985,0.000514,3.941704,-0.246410,0.943954
2,0.006882,2.893385,0.993349,217.668251,0.532579,344.808289,867.779617,6.458872,8.137255,0.001378,1.918072,-0.532217,0.997858
3,0.003499,4.302194,0.996611,635.155855,0.487667,419.748037,2536.321228,7.427680,9.296058,0.001114,2.151805,-0.576310,0.999560
4,0.004195,2.290831,0.996602,337.281020,0.566799,398.082177,1346.833250,7.125867,8.626036,0.001386,1.785225,-0.610392,0.999605
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,0.002677,57.812529,0.830829,170.920784,0.221546,320.265423,625.870606,6.560010,10.170253,0.000569,3.722253,-0.216835,0.902833
1496,0.001832,303.161384,0.581122,361.825452,0.144569,332.011049,1144.140424,6.727520,11.359547,0.000402,4.823127,-0.121160,0.681015
1497,0.001376,66.009060,0.936595,520.635955,0.211837,329.368175,2016.534761,7.447397,11.145206,0.000533,3.815359,-0.297963,0.977412
1498,0.001664,17.757943,0.985448,610.305641,0.312038,315.583353,2423.464622,7.476375,10.325215,0.000752,2.986811,-0.426834,0.996448
1499,0.003479,14.323238,0.961211,184.725554,0.344630,331.155853,724.578978,6.650069,9.313381,0.000842,2.819624,-0.378262,0.986608

In [32]:
path_lst=[]
for f in glob.glob('Data(image)/train/righttop/*.jpg'): ###train_image改成放所有圖片的資料夾
    path_lst.append(f)

f1=f2=f3=f4=f5=f6=f7=f8=f9=f10=f11=f12=f13=np.empty(0)

for image in path_lst:
    img = cv2.imread(image)
    feature = mahotas.features.haralick(img).mean(axis =0)

    f1 = np.append(f1,feature[0])
    f2 = np.append(f2,feature[1])
    f3 = np.append(f3,feature[2])
    f4 = np.append(f4,feature[3])
    f5 = np.append(f5,feature[4])
    f6 = np.append(f6,feature[5])
    f7 = np.append(f7,feature[6])
    f8 = np.append(f8,feature[7])
    f9 = np.append(f9,feature[8])
    f10 = np.append(f10,feature[9])
    f11 = np.append(f11,feature[10])
    f12 = np.append(f12,feature[11])
    f13 = np.append(f13,feature[12])

In [33]:
df_rt = pd.DataFrame([f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,f11,f12,f13], 
             index = ['f1','f2','f3','f4','f5','f6','f7','f8','f9','f10','f11','f12','f13']).transpose()

In [61]:
df_rt.rename(columns= lambda x:'rt_' + x, inplace = True)
df_rt

,rt_f1,rt_f2,rt_f3,rt_f4,rt_f5,rt_f6,rt_f7,rt_f8,rt_f9,rt_f10,rt_f11,rt_f12,rt_f13
0,0.001329,720.343318,0.116250,407.576514,0.119539,356.231133,909.962740,6.838585,12.086712,0.000359,5.405792,-0.091142,0.463520
1,0.001523,86.733712,0.915632,513.919588,0.203567,356.427588,1968.944640,7.325674,11.142417,0.000508,3.976875,-0.267489,0.961731
2,0.004513,3.145900,0.995798,374.375837,0.519206,361.372843,1494.357448,6.923578,8.651671,0.001280,1.962933,-0.559649,0.999051
3,0.003573,4.136606,0.997128,720.421753,0.500857,413.792831,2877.550406,7.474865,9.298291,0.001131,2.133283,-0.586615,0.999641
4,0.003513,2.491070,0.997311,463.488924,0.555160,408.820832,1851.464625,7.296255,8.839686,0.001331,1.832902,-0.615596,0.999703
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,0.002904,51.420268,0.836249,157.051226,0.227714,318.427446,576.784636,6.478726,10.019757,0.000629,3.653132,-0.218191,0.903696
1496,0.001702,330.791713,0.580618,394.384579,0.142197,336.673119,1246.746603,6.812900,11.507897,0.000396,4.883021,-0.122323,0.689715
1497,0.001104,67.146578,0.956386,769.786398,0.212062,328.701037,3011.999015,7.710036,11.408297,0.000531,3.827307,-0.323553,0.986346
1498,0.002083,19.495363,0.972586,355.595678,0.304206,335.920627,1402.887349,7.186494,10.092476,0.000725,3.041625,-0.391626,0.992844
1499,0.003156,14.973059,0.963564,205.531570,0.338223,334.663182,807.153221,6.760998,9.463280,0.000850,2.846007,-0.383032,0.988180

In [ ]:
df_rb.rename(columns= lambda x:'rb_' + x, inplace = True)
df_rb

In [63]:
df_f65 = pd.concat([df_full, df_lb, df_lt, df_rb, df_rt], axis =1)
df_f65

,full_f1,full_f2,full_f3,full_f4,full_f5,full_f6,full_f7,full_f8,full_f9,full_f10,...,rt_f4,rt_f5,rt_f6,rt_f7,rt_f8,rt_f9,rt_f10,rt_f11,rt_f12,rt_f13
0,0.001354,659.317620,0.157167,391.132306,0.121252,346.768587,905.211606,6.840575,12.089976,0.000363,...,407.576514,0.119539,356.231133,909.962740,6.838585,12.086712,0.000359,5.405792,-0.091142,0.463520
1,0.001497,91.209170,0.909179,502.079395,0.200690,358.785207,1917.108412,7.329339,11.208077,0.000504,...,513.919588,0.203567,356.427588,1968.944640,7.325674,11.142417,0.000508,3.976875,-0.267489,0.961731
2,0.005265,3.084968,0.995852,371.720231,0.523585,357.885009,1483.795954,6.817557,8.538440,0.001253,...,374.375837,0.519206,361.372843,1494.357448,6.923578,8.651671,0.001280,1.962933,-0.559649,0.999051
3,0.003159,4.283336,0.996857,681.378381,0.491811,413.949971,2721.230186,7.505229,9.382262,0.001118,...,720.421753,0.500857,413.792831,2877.550406,7.474865,9.298291,0.001131,2.133283,-0.586615,0.999641
4,0.003536,2.498093,0.997002,416.623572,0.555521,406.948885,1663.996196,7.267164,8.833541,0.001332,...,463.488924,0.555160,408.820832,1851.464625,7.296255,8.839686,0.001331,1.832902,-0.615596,0.999703
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,0.001614,66.861090,0.950800,679.505644,0.215053,351.011115,2651.161484,7.339455,11.037201,0.000535,...,157.051226,0.227714,318.427446,576.784636,6.478726,10.019757,0.000629,3.653132,-0.218191,0.903696
1496,0.001704,364.121754,0.447507,329.527395,0.138495,332.144321,953.987826,6.729030,11.561065,0.000392,...,394.384579,0.142197,336.673119,1246.746603,6.812900,11.507897,0.000396,4.883021,-0.122323,0.689715
1497,0.001199,67.339221,0.949033,660.564422,0.211137,331.220127,2574.918467,7.619690,11.357897,0.000530,...,769.786398,0.212062,328.701037,3011.999015,7.710036,11.408297,0.000531,3.827307,-0.323553,0.986346
1498,0.001740,18.464517,0.980740,479.347234,0.308725,326.214935,1898.924419,7.386130,10.281776,0.000733,...,355.595678,0.304206,335.920627,1402.887349,7.186494,10.092476,0.000725,3.041625,-0.391626,0.992844
1499,0.003303,14.546463,0.961501,188.949583,0.341687,333.356969,741.251869,6.695808,9.390440,0.000837,...,205.531570,0.338223,334.663182,807.153221,6.760998,9.463280,0.000850,2.846007,-0.383032,0.988180